### ISSUE TITLE
Bug - No double click Zigbee2MQTT Ikea E1743

### ISSUE THREAD

**Issue by thelaw911** [lsismeiro/awesome-ha-blueprints#16]
### Blueprint name

Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer

### Home Assistant Core Version

2024.6.2

### Home Assistant Installation Type

Home Assistant Container

### Description

When adding a double click action and then double clicking the button, the action will not fire. Under step configuration i get the following message:
condition: and
conditions:
  - >-
    {%- set trigger_action -%} {%- if integration_id == "zigbee2mqtt" -%} {{
    trigger.event.data.new_state.state }} {%- elif integration_id == "deconz"
    -%} {{ trigger.event.data.event }} {%- elif integration_id == "zha" -%} {{
    trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{
    trigger.event.data.args|join("_") }} {%- endif -%} {%- endset -%} {{
    trigger_action not in ["","None"] }}
  - >-
    {{ integration_id != "zigbee2mqtt" or trigger.event.data.new_state.state !=
    trigger.event.data.old_state.state }}

[trace automation.test_studeerkamer 2024-06-20T13_02_58.780185+00_00.json](https://github.com/user-attachments/files/15914302/trace.automation.test_studeerkamer.2024-06-20T13_02_58.780185%2B00_00.json)

### Automation YAML config

```yaml
alias: test studeerkamer
description: ""
use_blueprint:
  path: lsismeiro/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.aan_uit_studeerkamer_action
    helper_last_controller_event: input_text.last_controller_event
    action_button_down_double:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.bureaulamp
    button_down_double_press: true
```

### To Reproduce

1. Set up blueprint
2. Double click button
3. See error

### Expected behavior

I expected that the on/off button would have been updated like the 5-button controller. 
So a double click would trigger an action.

### Actual Behaviour

Nothing happens.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
