### ISSUE TITLE
Bug - IKEA E2001/E2002 ZHA Throws warning when device goes offline

### ISSUE THREAD

**Issue by mibauzas** [lsismeiro/awesome-ha-blueprints#20]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2024.7.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

When the device goes offline, it triggers a ZHA event that lacks the attribute 'command' and generates the following warning in the logs:

`Template variable warning: 'dict object' has no attribute 'command' when rendering '{%- set trigger_action -%} {%- if integration_id == "zigbee2mqtt" -%} {{ trigger.event.data.new_state.state }} {%- elif integration_id == "deconz" -%} {{ trigger.event.data.event }} {%- elif integration_id == "zha" -%} {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }} {%- endif -%} {%- endset -%} {{ trigger_action not in ["","None"] }}`

### Automation YAML config

```yaml
alias: N2 Cocina
description: ""
use_blueprint:
  path: lsismeiro/ikea_e2001_e2002.yaml
  input:
    integration: ZHA
    controller_device: c8c32c11b730114daa60c79704008c9b
    helper_last_controller_event: input_text.ikea_remote_kitchen
    action_button_up_short:
      - service: timer.start
        data: {}
        target:
          entity_id: timer.pump_timer
    action_button_down_short:
      - service: timer.cancel
        data: {}
        target:
          entity_id: timer.pump_timer
```

### To Reproduce

1. Press any button on the controller to wake it up.
2. Do not press any other button until the event for device offline triggers. It takes more than 4 hours.

### Expected behavior

Ignore the event when the device goes offline.

### Actual Behaviour

Warning appears in logs.

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Additional context

Maybe it's not the best solution, but checking if the attribute is defined fixed the issue:

In blueprints/controllers/ikea_e2001_e2002/ikea_e2001_e2002.yaml line 386 replace:

```
{%- elif integration_id == "zha" -%}
{{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
{%- endif -%}
```

with:

```
{%- elif integration_id == "zha" -%}
{%- if trigger.event.data.command is defined -%}
{{ trigger.event.data.command}}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
{%- else -%}
{{""}} 
{%- endif -%} 
```

I hope it helps
