### ISSUE TITLE
Dimming does not work - Lights just dim all the way down to off and then back all the way to full

### ISSUE THREAD

**Issue by remirr** [lsismeiro/awesome-ha-blueprints#21]
### Blueprint name

Light Hook

### Home Assistant Core Version

2024.7.0

### Home Assistant Installation Type

Home Assistant Container

### Description

When using this Blueprint, dim up and down does not work. When pressing dim down (long hold) the lights just dim all the way to off. When holding dim up, the lights just go all the way up until on.

https://github.com/lsismeiro/awesome-ha-blueprints/blob/9ddf8da000390462f0088192463c9138f123f849/blueprints/controllers/ikea_e2001_e2002/ikea_e2001_e2002.yaml

### Automation YAML config

```yaml
alias: Controller - IKEA E2001/E2002 STYRBAR Remote control
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.table_lights_remote_action
    helper_last_controller_event: input_text.table_lights_remote
    button_up_long_max_loop_repeats: 500
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

To dim down step by step

### Actual Behaviour

dims all the way down

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
