### ISSUE TITLE
UndefinedError: 'dict object' has no attribute 'event'

### ISSUE THREAD

**Issue by TylonHH** [lsismeiro/awesome-ha-blueprints#24]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2024.10.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I set up the controller automation with the corresponding blueprint. I also defined a text helper.

### Automation YAML config

```yaml
alias: Hook - Light grosses Licht Hue 4 Switch
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: bea901a129595a09878b7c9ce0928b55
    controller_entity: sensor.hue_4_taster_action
    controller_model: Philips 324131092621 Hue Dimmer switch
    light: light.hue_wohnzimmer_gross
    light_color_mode: Auto
```

### To Reproduce

I just run the automation and checked the trace

### Expected behavior

Automation get fired

### Actual Behaviour

Fehler: UndefinedError: 'dict object' has no attribute 'event'

variables:
  action: '{{ trigger.event.data.action }}'

### Additional Details

- [X] I'd like to help developing a fix for this issue.
