### ISSUE TITLE
Bug - E1744 rotates continuously with light brightness or media volume

### ISSUE THREAD

**Issue by scorednever** [lsismeiro/awesome-ha-blueprints#25]
### Blueprint name

ikea_e1744

### Home Assistant Core Version

2024.10.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I've imported the new blueprint for the Ikea E1744 controller (with light and media hooks) from the following repository: https://github.com/lsismeiro/awesome-ha-blueprints/tree/main/blueprints. I then created automations using these blueprints.

However, when rotating the controller (either left or right), the associated action (light brightness or media volume) continues to change continuously, even after releasing the controller, until it reaches the maximum or minimum value. The change only stops if the button is clicked.

### Automation YAML config

```yaml
alias: black 3 volume bp oct24
description: ""
use_blueprint:
  path: lsismeiro/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.ikea_volume_black_3_action
    helper_last_controller_event: input_text.ikea_volume_black_3_blueprint_helper
    rotate_left_loop: false
    rotate_right_loop: false


alias: black 3 volume light test
description: ""
use_blueprint:
  path: lsismeiro/light.yaml
  input:
    controller_device: 22c5a65e11aa6bec180a3162f02fcfd7
    controller_entity: sensor.ikea_volume_black_3_action
    controller_model: IKEA E1744 SYMFONISK Rotary Remote
    light: light.bedroom_ceiling

alias: black 3 volume squeeze bedroom
description: ""
use_blueprint:
  path: lsismeiro/media_player.yaml
  input:
    controller_device: 22c5a65e11aa6bec180a3162f02fcfd7
    controller_entity: sensor.ikea_volume_black_3_action
    controller_model: IKEA E1744 SYMFONISK Rotary Remote
    media_player: media_player.squeeze_bedroom
    volume_steps_short: 99
    volume_steps_long: 99
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

 The rotary action should stop adjusting brightness or volume when the controller is no longer being rotated.

### Actual Behaviour

Volume / brightness changes continuously and only stops if the button is clicked to pause / play, toggle light. 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
