### ISSUE TITLE
Bug -  Blueprint fails to change color with HA 2025 and Ikea Styrbar

### ISSUE THREAD

**Issue by elaak** [lsismeiro/awesome-ha-blueprints#37]
### Blueprint name

blueprints/hooks/light/light.yaml

### Home Assistant Core Version

2025.1.0

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Using the IKEA Styrbar remote to control the color temperature (right or left clicks) of my IKEA Trådfri lights, fails. I have added a Screenshot which shows the trace but I am not knowledgeable yet about Home assistant to find out why this is happening. From what I read I  

### Automation YAML config

```yaml
alias: Bedroom light 1 hook
description: ""
use_blueprint:
  path: lsismeiro/light.yaml
  input:
    controller_entity: sensor.bedroom_light_remote_action
    controller_model: IKEA E2001/E2002 STYRBAR Remote control (#2)
    light: light.bedroom_light_1
    smooth_power_off: true
    smooth_power_on: true
    light_color_mode: Color Temperature
    force_brightness: false
```

### To Reproduce

1. Setup automation
2. Click right or left on remote
3. Nothing happens
4. Review trace to see what went wrong

### Expected behavior

Lights change color temperature

### Actual Behaviour

Nothing

### Additional Details

- [x] I'd like to help developing a fix for this issue.

### Screenshots

![image](https://github.com/user-attachments/assets/51e3183d-a006-4730-b144-f66cc3e77f19)
This is the error in the trace of the hook
