### ISSUE TITLE
Bug - No double click Zigbee2MQTT Ikea E2001/E2002

### ISSUE THREAD

**Issue by Arubinu** [lsismeiro/awesome-ha-blueprints#38]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2025.1.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hello, I tried to add an action that allows me to turn off all my bulbs when I double press the bottom button, while a single press only turns off one.

To my greatest surprise it only turned off one. After several tries I managed to activate it but not during a double press.

The results of this deposit do not talk about this detail so I will share it with you.

### Automation YAML config

```yaml
alias: Chambre Alvin Interrupteur Intelligent
description: ""
use_blueprint:
  path: lsismeiro/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_device: ba995b5117409828504f09ec6e19f2c7
    controller_entity: sensor.chambre_alvin_interrupteur_action
    helper_last_controller_event: input_text.chambre_alvin_interrupteur
    button_left_long_loop: true
    button_right_long_loop: true
    button_up_long_loop: true
    button_down_long_loop: true
    action_button_left_short:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
            sequence:
              - action: input_number.decrement
                metadata: {}
                data: {}
                target:
                  entity_id: input_number.chambre_alvin_interrupteur_intelligent
    action_button_right_short:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                below: 1
            sequence:
              - action: input_number.increment
                metadata: {}
                data: {}
                target:
                  entity_id: input_number.chambre_alvin_interrupteur_intelligent
    action_button_up_short:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -3
                below: -1
            sequence:
              - parallel:
                  - type: turn_on
                    device_id: 6b68bae2d9373b6a46e1c625d3ab7273
                    entity_id: 9dd87ba55d9bb4a11a6d6aa9f7a69e29
                    domain: light
                  - type: turn_on
                    device_id: b12f9ba6567795e1e7e39741dc2b6498
                    entity_id: 4a6108305904a2a1b383036fbc50931d
                    domain: light
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
                below: 0
            sequence:
              - action: light.turn_on
                metadata: {}
                data: {}
                target:
                  device_id: ef419be33a51be10928bd70725474cff
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -1
                below: 1
            sequence:
              - if:
                  - condition: device
                    type: is_on
                    device_id: 1a2c8b88dd8ae21d8784731fecf49ab6
                    entity_id: 8e10e8229d59a3ea35505473d051cdb6
                    domain: light
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 0
                then:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_pct: 100
                    target:
                      device_id: 1a2c8b88dd8ae21d8784731fecf49ab6
                else:
                  - action: light.turn_on
                    metadata: {}
                    data: {}
                    target:
                      device_id: 1a2c8b88dd8ae21d8784731fecf49ab6
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: 0
                below: 2
            sequence:
              - type: turn_on
                device_id: 27e82948e84c853475a50cd3c275f67d
                entity_id: 314095659b5b4d595b7cf724ba607a4f
                domain: switch
    action_button_down_short:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -3
                below: -1
            sequence:
              - parallel:
                  - type: turn_off
                    device_id: 6b68bae2d9373b6a46e1c625d3ab7273
                    entity_id: 9dd87ba55d9bb4a11a6d6aa9f7a69e29
                    domain: light
                  - type: turn_off
                    device_id: b12f9ba6567795e1e7e39741dc2b6498
                    entity_id: 4a6108305904a2a1b383036fbc50931d
                    domain: light
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
                below: 0
            sequence:
              - action: light.turn_off
                metadata: {}
                data: {}
                target:
                  device_id: ef419be33a51be10928bd70725474cff
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -1
                below: 1
            sequence:
              - action: light.turn_off
                metadata: {}
                data: {}
                target:
                  device_id: 1a2c8b88dd8ae21d8784731fecf49ab6
    action_button_left_long:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -3
                below: -1
            sequence:
              - parallel:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      kelvin: >-
                        {{
                        states['light.chambre_alvin_key_light_gauche'].attributes.color_temp_kelvin
                        | int - 200 }}
                    target:
                      device_id: 6b68bae2d9373b6a46e1c625d3ab7273
                  - action: light.turn_on
                    metadata: {}
                    data:
                      kelvin: >-
                        {{
                        states['light.chambre_alvin_key_light_droite'].attributes.color_temp_kelvin
                        | int - 200 }}
                    target:
                      device_id: b12f9ba6567795e1e7e39741dc2b6498
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
                below: 0
            sequence:
              - action: script.changement_de_couleur_circulaire
                data:
                  light: light.chambre_alvin_spot
                  reverse: true
                  step: 45
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -1
                below: 1
            sequence:
              - action: script.changement_de_couleur_circulaire
                data:
                  light: light.chambre_alvin_plafonnier
                  reverse: true
                  step: 45
    action_button_right_long:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -3
                below: -1
            sequence:
              - parallel:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      kelvin: >-
                        {{
                        states['light.chambre_alvin_key_light_gauche'].attributes.color_temp_kelvin
                        | int + 200 }}
                    target:
                      device_id: 6b68bae2d9373b6a46e1c625d3ab7273
                  - action: light.turn_on
                    metadata: {}
                    data:
                      kelvin: >-
                        {{
                        states['light.chambre_alvin_key_light_droite'].attributes.color_temp_kelvin
                        | int + 200 }}
                    target:
                      device_id: b12f9ba6567795e1e7e39741dc2b6498
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
                below: 0
            sequence:
              - action: script.changement_de_couleur_circulaire
                data:
                  light: light.chambre_alvin_spot
                  reverse: false
                  step: 45
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -1
                below: 1
            sequence:
              - action: script.changement_de_couleur_circulaire
                data:
                  light: light.chambre_alvin_plafonnier
                  reverse: false
                  step: 45
    action_button_up_long:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -3
                below: -1
            sequence:
              - parallel:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_step_pct: 2
                    target:
                      device_id: 6b68bae2d9373b6a46e1c625d3ab7273
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_step_pct: 2
                    target:
                      device_id: b12f9ba6567795e1e7e39741dc2b6498
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
                below: 0
            sequence:
              - data:
                  brightness_step_pct: 2
                action: light.turn_on
                target:
                  device_id: ef419be33a51be10928bd70725474cff
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -1
                below: 1
            sequence:
              - data:
                  brightness_step_pct: 2
                action: light.turn_on
                target:
                  device_id: 1a2c8b88dd8ae21d8784731fecf49ab6
    action_button_down_long:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -3
                below: -1
            sequence:
              - parallel:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_step_pct: -2
                    target:
                      device_id: 6b68bae2d9373b6a46e1c625d3ab7273
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_step_pct: -2
                    target:
                      device_id: b12f9ba6567795e1e7e39741dc2b6498
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -2
                below: 0
            sequence:
              - data:
                  brightness_step_pct: -2
                action: light.turn_on
                target:
                  device_id: ef419be33a51be10928bd70725474cff
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: -1
                below: 1
            sequence:
              - data:
                  brightness_step_pct: -2
                action: light.turn_on
                target:
                  device_id: 1a2c8b88dd8ae21d8784731fecf49ab6
          - conditions:
              - condition: numeric_state
                entity_id: input_number.chambre_alvin_interrupteur_intelligent
                above: 0
                below: 2
            sequence:
              - type: turn_off
                device_id: 27e82948e84c853475a50cd3c275f67d
                entity_id: 314095659b5b4d595b7cf724ba607a4f
                domain: switch
    button_up_double_press: false
    button_down_double_press: true
    action_button_down_double:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id:
            - 1a2c8b88dd8ae21d8784731fecf49ab6
            - ef419be33a51be10928bd70725474cff
            - 6b68bae2d9373b6a46e1c625d3ab7273
            - b12f9ba6567795e1e7e39741dc2b6498
        enabled: true
    helper_double_press_delay: 500
```

### To Reproduce

My double press action activates when I press the bottom button once, but have pressed any other front button within the specified time.

- Press the top button, left, or right, once
- Within 500ms press the bottom button only once,
- Double-press action activates.

### Expected behavior

Let the action occur when a quick double press of the bottom button that is exposed.
I specify that I tried with a greater delay and/or the action exposed.

### Actual Behaviour

Activates the action of simply pressing the bottom button.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

I don't know what that implies, but I'm here if there's a need for testing.
