### ISSUE TITLE
Bug - ikea_e2001_e2002 looping long press is not consistent

### ISSUE THREAD

**Issue by chuckleplant** [lsismeiro/awesome-ha-blueprints#39]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2025.1.2

### Home Assistant Installation Type

Home Assistant Container

### Description

When using long button looping press action to control a light's brightness, the action only acts twice at most. Sometimes triggers after releasing the button. Tried with and without debounce delay.

### Automation YAML config

```yaml
alias: Office Styrbar
description: ""
use_blueprint:
  path: lsismeiro/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.office_remote_1_action
    helper_last_controller_event: input_text.office_styrbar
    action_button_up_long:
      - device_id: 623b1b001963e457f5c05f73c421372c
        domain: light
        entity_id: 4337bf966193d45461b3543a120cbe02
        type: brightness_increase
    action_button_down_long:
      - device_id: 623b1b001963e457f5c05f73c421372c
        domain: light
        entity_id: 4337bf966193d45461b3543a120cbe02
        type: brightness_decrease
    button_up_long_loop: true
    button_down_long_loop: true
    helper_debounce_delay: 50
```

### To Reproduce

* Configure light brightness controll to looping long presses of the remote
* Long press trying to go to full brightness or min brightness

### Expected behavior

The light goes to either full or min brightness somewhat smoothly. The time between brightness steps is consistent.

### Actual Behaviour

Light will only go two brightness steps in any direction. After trying to go in one direction and stopping, when I attempt to go at the other direction the first step the light does is in the previous commanded direction. 

### Additional Details

- [x] I'd like to help developing a fix for this issue.

### Additional context

Here's a video of the logs and the state of brightness. At the start i press left and right arrows just to identify where in the logs the process starts. Then i proceed to decrease brightness by holding down button for about 10 seconds.

https://youtu.be/xuySSo_n544
